### ISSUE TITLE
About curry implementation

### ISSUE THREAD

**Issue by frankyxhl** [shindakioku/fpfantasy#1]
Hi, @shindakioku 

Nice package!

I saw your Curry's warnings at https://shindakioku.github.io/documentation.html#curring-section

How about this package's implementation?
https://pub.dartlang.org/packages/curry

**Comment by shindakioku** [comment]
Hi. Thank you!
Yep, interesting implementation, but there using dart mirrors. This is not
the allowed in flutter and (maybe) front-end.
Is main problem in -
> Warning: 'call' is used reflectively but not in MirrorsUsed. This will
break minified code.
If you wanna, you can try implementation it without mirrors and make PR to
repository.
Thank you, good luck!

**Comment by frankyxhl** [comment]
Thanks for reply.

Sure, I will try it later. 

Will do some research first because I just learned Flutter and Dart only one month. I do believe function programming can leverage Flutter.

I used RamdaJs in JavaScript and toolz in Python quite often(spent years in Haskell but still a newbie T_T ) but never think about its bottom implementation.
